name: update-gh-activity
on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs in 15 minutes from now
    - cron: "15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update GitHub Activity'
          COMMIT_NAME: GitHub Activity Readme
